services:
  nginx-proxy:
    image: nginx:latest
    container_name: fixflow-reverse-proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      public_face:
      backend:

  db:
    image: postgres:16
    container_name: fixflow-db
    restart: always
    environment:
      POSTGRES_DB: fixflow
      POSTGRES_USER: fixflow
      POSTGRES_PASSWORD: fixflow_local_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixflow -d fixflow"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - fixflow-db-data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: ./fixflow.web
    container_name: fixflow-web
    restart: always
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=fixflow;Username=fixflow;Password=fixflow_local_dev"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  adminer:
    image: adminer
    container_name: fixflow-adminer
    restart: always
    ports:
        - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  public_face:
    driver: bridge

volumes:
  fixflow-db-data: